Repository Raidro/Rentech, pull requests merged in 2020-10, with the labels that each got.

#8 Adição no README e exclusão do arquivo de Canvas
  Canvas de modelo de negocio.txt
  README.md
Labels: documentation

#12 Coloca os modelos de canvas no projeto
  Modelos de Canvas/Business Model Canvas.pdf
  Modelos de Canvas/Canvas de proposta de valor.pdf
  Modelos de Canvas/Pitch Canvas.pdf
Labels: documentation

#14 Adicionada análise sobre os 10 tipos de inovação
  Tipos de Inovação/README.md
Labels: hacktoberfest-accepted

#15 Corrigido erros de gramática
  Tipos de Inovação/README.md
Labels: hacktoberfest-accepted

#18 Inclusão de texto do Business Model Canvas
  Modelos de Canvas/Business Model Canvas/README.md
Labels: hacktoberfest-accepted

#17 Transfere o que victor escreveu do docx pro README
  README.md
Labels: documentation, hacktoberfest-accepted

#20 alter in readme na seção de segmento de cliente
  README.md
Labels: hacktoberfest-accepted

#19 Pitch Canvas
  README.md
Labels: documentation, hacktoberfest-accepted

#21 Corrige Erros Gramaticais
  README.md
Labels: documentation, hacktoberfest-accepted

#22 Badge
  README.md
Labels: enhancement, hacktoberfest-accepted

#23 Organizar a estrutura do projeto
  Modelos de Canvas/Business Model Canvas/README.md
  Modelos de Canvas/README.md
  README.md
Labels: hacktoberfest-accepted

#24 Ajustes textuais e nome de membros da equipe
  README.md
Labels: hacktoberfest-accepted

#25 Adicionado a Matriz de Inovação
  README.md
  img/matriz-de-inovacao.jpg
Labels: hacktoberfest-accepted
